### PR TITLE
Add a basic Travis configuration that runs flake8 and 'bob --help'

### PR DESCRIPTION
**Pull request by edmorley**
* Fixes various flake8 import and whitespace warnings.
* Adds a configuration file for Travis, which runs flake8 and `bob --help` as a first step towards having a test suite (#31).

### CODE REVIEW

**Comment by kennethreitz** [comment]
@edmorley build failed!

**Comment by kennethreitz** [comment]
Looks like we only support 2.7 :)

**Comment by edmorley** [comment]
> build failed!

I missed out the `pip install .` :-)

> Looks like we only support 2.7 :)

I've marked the Python 3 parts as being allowed to fail (but they still run, which allows for easier iteration), and I'll file an issue for adding support.

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request merged**
