### PR TITLE
Allow fallback to anon UPSTREAM_S3_BUCKET access

### PR DESCRIPTION
**Pull request by dzuelke**
An `UPSTREAM_S3_BUCKET` should usually allow "Everyone" for listing bucket contents.
If the S3 credentials for the normal bucket do not explicitly have access, a 403 will occur.
In that case, we re-try fetching the upstream bucket with anonymous authentication.

Try this out please, @stof

### CODE REVIEW

**Comment by stof** [comment]
I confirm that this works

**Comment by dzuelke** [comment]
🎉

**Comment by stof** [comment]
@dzuelke any change to merge and release this ? It is painful for me to manage my heroku-php-exts repository as I have to force installing this WIP branch to be able to access deps in the upstream repo.

**Comment by dzuelke** [comment]
Oh wow sorry @stof, I'll merge and tag and release ASAP!

**Pull request merged**
